src/here_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('users.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    # Route for processing uploaded files
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from .views import index, by_category, detail


app_name = 'main'
urlpatterns = [
    # path('accounts/login/', HerePointLoginView.as_view(), name='login'),
    path('', index, name='index'),
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
]

src/users/urls.py
from django.urls import path

from .views import (HerePointLoginView, HerePointLogoutView, 
                    ChangeUserInfoView, RegisterDoneView, 
                    RegisterUserView, HerePointPasswordChangeView,
                    DeleteUserView)
from .views import (profile, profile_place_add, 
                    profile_place_delete, profile_place_change)


app_name = 'users'
urlpatterns = [
    path('profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterUserView.as_view (), name='register'),
    path('profile/change/<int:pk>/', profile_place_change, name='place_change'),
    path('profile/delete/<int:pk>/', profile_place_delete, name='place_delete'),
    path('profile/add/', profile_place_add, name='place_add'),
    path('profile/', profile, name='profile'),
    path('login/', HerePointLoginView.as_view(), name='login'),
    path('logout/', HerePointLogoutView.as_view(), name='logout'),
    path('profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('profile/password/change/', 
         HerePointPasswordChangeView.as_view(),
         name='password_change'),
]

src/users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


class AdvUser(AbstractUser):
    is_activated = models.BooleanField(
            default=True,
            db_index=True,
            verbose_name='Прошел активацию?')
    send_messages = models.BooleanField(
            default=True,
            verbose_name='Получать оповещения о новых местах?'
            )
    
    def __str__(self):
        return self.username


    class Meta(AbstractUser.Meta):
        pass

src/users/forms.py
from django import forms
from django.forms import inlineformset_factory
from django.contrib.auth import password_validation
from django.core.exceptions import ValidationError


from .models import AdvUser
from main.models import Place, AdditionalImage


class PlaceForm(forms.ModelForm):
    class Meta:
        model = Place
        fields = '__all__'
        widgets = {'author': forms.HiddenInput}

AIFormSet = inlineformset_factory(Place, AdditionalImage, fields='__all__')


class ChangeUserInfoForm(forms.ModelForm):
    """ Form for change main info about user """
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    username = forms.CharField(max_length=15, required=True, label='Никнейм')
    first_name = forms.CharField(max_length=15, required=True, label='Имя')
    last_name = forms.CharField(max_length=15, required=True, label='Фамилия')
    
    class Meta:
        model = AdvUser
        fields = ('email', 'username', 'first_name', 
                  'last_name', 'send_messages')


class RegisterUserForm(forms.ModelForm):
    email = forms.EmailField(required=True, label='Адрес электронной почты')
    username = forms.CharField(max_length=15, required=True, label='Никнейм')
    first_name = forms.CharField(max_length=15, required=True, label='Имя')
    last_name = forms.CharField(max_length=15, required=True, label='Фамилия')
    password1 = forms.CharField(label='Пароль', widget=forms.PasswordInput,
            help_text=password_validation.password_validators_help_text_html())
    password2 = forms.CharField(label='Пароль (повторно)',
            widget=forms.PasswordInput,
            help_text='Повторите пароль')

    def clean_password1(self):
        password1 = self.cleaned_data['password1']
        try:
            password_validation.validate_password(password1)
        except forms.ValidationError as error:
            self.add_error('password1', error)
        return password1

    def clean(self):
        super().clean()
        password1 = self.cleaned_data['password1']
        password2 = self.cleaned_data['password2']
        if password1 and password2 and password1 != password2:
            errors = {'password2': ValidationError(
            'ВВеденные пароли не совпадают', code='password_mismath' )}
            raise ValidationError(errors)

    def save(self, commit=True):
        user = super().save(commit=False)
        user.set_password(self.cleaned_data['password1'])
        user.is_active = True
        user.is_activated = True        
        if commit:
            user.save()
        #user_registered.send(RegisterUserForm, instance=user)
        return user


    class Meta:
        model = AdvUser
        fields = {'username', 'email', 'password1', 'password2',
                  'first_name', 'last_name', 'send_messages'}

src/users/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView, LogoutView, PasswordChangeView
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.contrib.auth import logout
from django.contrib import messages
from django.views.generic.edit import UpdateView, CreateView, DeleteView
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic.base import TemplateView

from .models import AdvUser
from main.models import Place
from .forms import ChangeUserInfoForm, RegisterUserForm, PlaceForm, AIFormSet


@login_required
def profile_place_change(request, pk):
    place = get_object_or_404(Place, pk=pk)
    author = place.author
    if request.user.is_authenticated:
        if request.user.username == author.username:
            if request.method == "POST":
                form = PlaceForm(request.POST, request.FILES, instance=place)
                if form.is_valid():
                    place = form.save()
                    formset = AIFormSet(request.POST, request.FILES, instance=place)
                    if formset.is_valid():
                        formset.save()
                        messages.add_message(request, messages.SUCCESS, 'Объявление исправлено')
                        return redirect('users:profile')
            else:
                form = PlaceForm(instance=place)
                formset = AIFormSet(instance=place)
            context = {'form': form, 'formset': formset}
            return render(request, 'users/place_change.html', context)

@login_required
def profile_place_delete(request, pk):
    place = get_object_or_404(Place, pk=pk)
    if request.method == "POST":
        place.delete()
        return redirect('users:profile')
    else:
        context = {'place': place}
        return render(request, 'users/place_delete.html', context)

@login_required
def profile_place_add(request):
    if request.method == "POST":
        form = PlaceForm(request.POST, request.FILES)
        if form.is_valid():
            place = form.save()
            formset = AIFormSet(request.POST, request.FILES, instance=place)
            if formset.is_valid():
                formset.save()
                messages.add_message(request, messages.SUCCESS, 'Место добавлено')
                return redirect('users:profile')
    else:
        form = PlaceForm(initial={'author': request.user.pk})
        formset = AIFormSet()
    context = {'form': form, 'formset': formset}
    return render(request, 'users/add_place.html', context)


class ChangeUserInfoView(SuccessMessageMixin, LoginRequiredMixin, UpdateView):
    """ Controller-class change UserInfo """
    model = AdvUser
    template_name = 'users/change_user_info.html'
    form_class = ChangeUserInfoForm
    success_url = reverse_lazy("users:profile")
    success_message = 'Данные пользователя изменены'

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class DeleteUserView(LoginRequiredMixin, DeleteView):
    model = AdvUser
    template_name = 'users/delete_user.html'
    success_url = reverse_lazy('main:index')

    def setup(self, request, *args, **kwargs):
        self.user_id = request.user.pk
        return super().setup(request, *args, **kwargs)

    def post(self, request, *args, **kwargs):
        logout(request)
        messages.add_message(request, messages.SUCCESS,
                            'Пользователь удален')
        return super().post(request, *args, **kwargs)

    def get_object(self, queryset=None):
        if not queryset:
            queryset = self.get_queryset()
        return get_object_or_404(queryset, pk=self.user_id)


class RegisterUserView(CreateView):
    """ Controller-class rigister new users """
    model = AdvUser
    template_name = 'users/register_user.html'
    form_class = RegisterUserForm
    success_url = reverse_lazy('users:register_done')


class RegisterDoneView(TemplateView):
    """ Controller-class open pattern after registration """
    template_name = 'users/register_done.html'


class HerePointPasswordChangeView(
                SuccessMessageMixin, 
                LoginRequiredMixin,
                PasswordChangeView):
    """ Controller-class change user's password """
    template_name = 'users/password_change.html'
    success_url = reverse_lazy("users:profile")


class HerePointLogoutView(LoginRequiredMixin, LogoutView):
    """ Controller-class doing the logout"""
    template_name = 'users/logout.html'
    next_page = 'main:index'


class HerePointLoginView(LoginView):
    """ Controller-class doing the login """
    template_name = 'users/login.html'

@login_required
# login_required checking users for registration
def profile(request):
    """ Controller-class that display the user profile page """
    places = Place.objects.filter(author=request.user.pk)
    context = {'places': places}
    return render(request, 'users/profile.html', context)

src/users/templates/users/index.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Последние 10 мест</h2>
{% endblock %}

src/users/templates/users/login.html
{% extends "layout/basic.html" %}

{% block content %}
<h3 class="text-center mb-4">Вход</h3>
{% if user.authenticated %}
<h3 class="text-center mb-4">Вы уже выполнили вход</h3>
{% else %}
<form method="post">
	{% csrf_token %}
	<div class="form-group">
		<label for="text">Имя</label>
		<input name="username" type='text' class="form-control" id="text" placeholder="Введите имя">	
		<label for="pass">Пароль</label>
		<input name="password" type="password" class="form-control" id="pass" placeholder="Введите пароль">
	</div>
	<input type="hidden" name="next" value="{{ next }}">
	<input type="submit" value="Войти">
	<button type="button" onclick="document.location='{% url 'users:register' %}'" id="registration">Регистрация</button>
</form>
{% endif %}
{% endblock %}

src/users/templates/users/logout.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Выход</h2>
<p>Вы успешно вышли</p>
{% endblock %}

src/users/templates/users/password_change.html
{% extends "layout/basic.html" %}

{% block content %}
<h3 class="text-center mb-4">Смена пароля</h3>
<form method="post">
        {% csrf_token %}
        <div class="form-group">
                <label for="old_pass">Старый пароль</label>
                <input name="old_password" type="password" class="form-control" id="old_pass" placeholder="Старый пароль">
		<label for="new_pass1">Новый пароль</label>
                <input name="new_password1" type="password" class="form-control" id="new_pass1" placeholder="Новый пароль">
		<label for="new_pass2">Подтверждение нового пароля</label>
                <input name="new_password2" type="password" class="form-control" id="new_pass2" placeholder="Подтверждение нового пароля">
        </div>
        <input type="submit" value="Войти">
	<button onclick="document.location='{% url 'users:profile_change' %}'" type="button" class='back'>Назад</button>
</form>
{% endblock %}

src/users/templates/users/profile.html
{% load static %}
{% load thumbnail %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title></title>
    <!-- bootstrap 5 -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous"></script>
    <!-- jQuery -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script>


    <style>
        /* Monoserrat */
        @import url('https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap');
        /* Roboto */
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap');

        body, html {
            width: 100%;
            height: 100%;
            font-family: 'Roboto', sans-serif;
            color:black;    
        }

        #usericon {	
        }

        #logo {
            text-decoration:none;
            color: #2b2a2c;
            font-size: 30px;
            padding: 0px 0px 0px 25px;
            font-family: 'Cinzel', serif;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
            /* position: relative; */
        }

        #logo:after {
            content: "";
            /* display: block; */
            width: 100%;
            height: 2px;
            background-color: #2B2A2C;
            bottom: -5;
            left: 0;
            z-index: 1;
        }

        .nav-link {
            /*padding: 10px 30px; */
            /*font-family: 'Open Sans Condensed', sans-serif;*/
            margin-left: 30px;
            position: relative;

            font-size: 18px;
            color: #2B2A2C;
            text-transform: uppercase;
            font-weight: 500;
            text-decoration: none;

            /*border: 2px solid transparent;*/
            /*border-radius: 20px;*/
        }

        .nav-link:hover {
            opacity: .5;
        }

        #user-place {
            transition: transform .1s linear;
        }

        #user-place:hover {
            transform: translateY(-5px);
        }

        .div-avatar {
            background-size: cover;
            border-radius: 50%;
            width: 100%;
            object-fit: cover;
        }

        .img {
            width: 100%;
            height: 150px;
            object-fit: cover;
        }

        .show-div {
            background-color: red;
        }

        .places {
            transition: transform .1s linear;
        }

        .places:hover {
            transform: translateY(-5px);
        }
    </style>

</head>
<body background="{% static 'images/background.jpg' %}" style="background-size: cover; background-repeat: no-repeat; background-position: center center; background-attachment: fixed">
    <!-- Шапка -->
    <nav class="navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
            <a class="navbar-brand" style="margin: 8px;" href="{% url 'main:index' %}" id="logo">HerePoint</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse justify-content-end me-3" id="navbarResponsive">
                <ul class="navbar-nav ml-auto" style="align-items: center">
                    <li class="nav-item active">
                        {% if user.is_authenticated %}
                        <a href="{% url 'users:profile_place_add' %}" class="nav-link active text-center">Добавить место</a>
                        {% else %} 
                        <a href="{% url 'users:login' %}" class="nav-link active text-center">Добавить место</a>
                        {% endif %}
                    </li>
                    <li class="nav-item active">
                        <img onclick="document.location='{% url 'users:profile' %}'" class="nav-link" src="{% static 'images/avatar_new.jpg' %}" width="60" height="60" alt="" style="border-radius: 50%;" id="usericon">
                    </li>
                </ul>
            </div>
        </div>
    </nav>
    <hr class="mt-0" style="opacity: 0.2">

    <!-- Тело -->
    <div class="container">
        <div class="row mt-5">
            <!-- Данные пользователя -->
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-7 col-xl-7">
                <div class="row mt-1 mb-2 text-center">
                    <span class="fs-2"><strong>Данные пользователя</strong></span>
                </div>
                <div class="row" style="align-items: center;">
                    <!-- Изображение -->
                    <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 col-xl-5">
                        <img src="{% static 'images/avatar_new.jpg' %}" class="div-avatar rounded-circle">
                    </div>
                    <!-- Поля -->
                    <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 col-xl-7">
                        <div class="row" style="align-items: center">
                            <div class="col-4">
                                <label for="Email" class="fs-4">Email:</label>
                            </div>
                            <div class="col-8">
                                <input type="text" readonly class="form-control-plaintext fs-4" id="Email" value="{{ user.email }}">
                            </div>
                        </div>
                        <div class="row mt-1" style="align-items: center">
                            <div class="col-4">
                                <label for="Username" class="fs-4">Username:</label>
                            </div>
                            <div class="col-8">
                                <input type="text" readonly class="form-control-plaintext fs-4" id="Username" value="{{ user.username }}">
                            </div>
                        </div>
                        <div class="row mt-1" style="align-items: center">
                            <div class="col-4">
                                <label for="Name" class="fs-4">Name:</label>
                            </div>
                            <div class="col-8">
                                <input type="text" readonly class="form-control-plaintext fs-4" id="Name" value="{{ user.first_name }}">
                            </div>
                        </div>
                        <div class="row mt-1" style="align-items: center">
                            <div class="col-4">
                                <label for="Surname" class="fs-4">Surname:</label>
                            </div>
                            <div class="col-8">
                                <input type="text" readonly class="form-control-plaintext fs-4" id="Surname" value="{{ user.last_name }}">
                            </div>
                        </div>
                        <div class="row mt-1" style="align-items: center">
                            <div class="col-4">
                                <label for="City" class="fs-4">City:</label>
                            </div>
                            <div class="col-8">
                                <input type="text" readonly class="form-control-plaintext fs-4" id="City" value="City">
                            </div>
                        </div>
                    </div>
                </div>
                <!-- Кнопки -->
                <div class="row">
                    <button onclick="document.location='{% url 'users:profile_change' %}'" class="btn btn-outline-secondary mt-5 btn-lg">Редактировать профиль</button>	
                </div>
                <div class="row">
                    <button onclick="document.location='{% url 'users:logout' %}'" class="btn btn-outline-secondary mt-3 btn-lg ">Выйти</button>
                </div>
                <div class="row">
                    <button type="button" class="btn btn-outline-secondary mt-3 mb-5 btn-lg">Удалить аккаунт</button>
                </div>
            </div>
            <!-- Добавленные места -->
            <div class="col-xs-12 col-sm-12 col-md-12 col-lg-5 col-xl-5">
                <div class="row mt-1 mb-2 text-center">
                    <span class="fs-2"><strong>Добавленные места</strong></span>
                </div>
                {% if places %}
                <!-- Места -->
                    {% for place in places %}
                    <div class="container places">
                        <!-- Ссылка на место -->
                        {% with category=place.categories.all %}
                        {% for c in category %}
                        {% url 'main:detail' category_pk=c.pk pk=place.pk as url %}
                        <a href="{{ url }}{{ all }}" class="text-decoration-none" style="font-size: 15px; color: black">
                            <div class="row" style="align-items: center;">
                                <div class="col-xs-12 col-sm-12 col-md-7 col-lg-7 col-xl-7">
                                    <img class="img rounded" src="{% thumbnail place.image "300x300" %}">
                                </div>
                                <div class="col-xs-12 col-sm-12 col-md-5 col-lg-5 col-xl-5">
                                    <p class="mt-1 mb-1">{{ place.title }}</p>
                                    <hr style="margin: 0">
                                    <p class="mt-1 mb-1">{{ place.address }}</p>
                                    <hr style="margin: 0">
                                    <p class="mt-1 mb-1">Рейтинг: <span style="font-size:20px">4.7</span>/5</p>
                                </div>
                            </div>
                        </a>
                        {% endfor %}
                        {% endwith %}
                    </div>
                    <hr>
                    {% endfor %}
                </div>
                {% endif %}
            </div>
        </div>
    </div>
    
    <footer>
        <div class="container-fluid" style="padding-top: 5em;"></div>
    </footer>
    <script>
        // .avatar-div height = width script
        var cw = $('.div-avatar').width();
        $('.div-avatar').css({'height':cw+'px'});

        // .img height = width / 2 script
        var newh = $('.img').width() / 2;
        $('.img').css({'height':newh+'px'});
    </script>
</body>
</html>  

src/users/templates/users/profile_olg.html
{% load static %}
{% load thumbnail %}

<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/xhtml">
<head>
    <meta charset="utf-8" />
    <title></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">
    <style>
	@import url('https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap');
	#usericon {	
	}
	#logo {
		text-decoration:none;
		color: #2b2a2c;
		font-size: 30px;
		padding: 0px 0px 0px 25px;
		font-family: 'Cinzel', serif;
		font-family: 'Montserrat', sans-serif;
		font-weight: 600;
		position: relative;
	}
	#logo:after {
		content: "";
  		display: block;
  		width: 100%;
  		height: 2px;
  		background-color: #2B2A2C;
  		bottom: -5;
  		left: 0;
  		z-index: 1;
	}

	#user-place {
		transition: transform .1s linear;
	}

	#user-place:hover {
		transform: translateY(-5px);
	}

    </style>

</head>
<body background="{% static 'images/background.jpg' %}" style=" overflow: hidden;background-size: cover; background-repeat: no-repeat; background-position: center center; background-attachment: fixed ">
    <nav class="navbar-light">
        <a class="navbar-brand ms-5" href="#">
            <span class="fs-1"></span>
	</a>
	<!--<button class="btn btn-outline-secondary float-end me-5 mt-5 btn-lg">Профиль</button> -->
	<img onclick="document.location='{% url 'users:profile' %}'" class="float-end me-5 mt-5" src="{% static 'images/me2.jpg' %}" width="47" height="47" alt="" style="border-radius: 50%;" id="usericon">
	<!-- <button onclick="document.location='{% url 'users:register' %}'" class="btn btn-outline-secondary float-end me-5 mt-5 btn-lg ">Регистрация</button> -->
	<button onclick="document.location='{% url 'users:place_add' %}'" class="btn btn-outline-secondary float-end me-5 mt-5 btn-lg ">Добавить своё место</button>
	<a class="float-start me-5 mt-5" style="margin: 8px;" href="{% url 'main:index' %}" id="logo">HerePoint</a>
    </nav>
    <div class="row mt-5"></div>
    <div class="row mt-5">
        <div class="col-1"></div>
        <div class="col-7">
		<span class="fs-2 "><strong>Данные пользователя</strong></span>
        </div>
        <div class="col ">
            <span class="fs-2 "><strong>Добавленные места</strong></span>
        </div>
    </div>
    <div class="row mt-5" style="height: auto;">
        <div class="col-1" style="word-break: break-all;"></div>
        <div class="col-2">
            <div class="row">
		    <img class="" src="{% static 'images/me2.jpg' %}" width="270" height="290" alt="" style="border-radius: 50%;">
            </div>
            <div class="row">
		    <button onclick="document.location='{% url 'users:profile_change' %}'" class="btn btn-outline-secondary mt-5 btn-lg">Редактировать профиль</button>		   	   <button onclick="document.location='{% url 'users:logout' %}'" class="btn btn-outline-secondary mt-3 btn-lg ">Выйти</button>
            </div>
        </div>
        <div class="col-5">
            <div class="row">
		    <label for="Email" class="col-sm-4 col-form-label fs-3">Email:</label>
                <div class="col-sm-8">
			<input type="text" readonly class="form-control-plaintext fs-3" id="Email" value="{{ user.email }}">
                </div>
            </div>
	    <div class="row">
		<label for="Username" class="col-sm-4 col-form-label fs-3">Username:</label>
		<div class="col-sm-8">
			<input type="text" readonly class="form-control-plaintext fs-3" id="Username" value="{{ user.username }}">
		</div>
	    </div>
            <div class="row">
                <label for="Name" class="col-sm-4 col-form-label fs-3">Name:</label>
                <div class="col-sm-8">
			<input type="text" readonly class="form-control-plaintext fs-3" id="Name" value="{{ user.first_name }}">
                </div>
            </div>
            <div class="row">
                <label for="Surname" class="col-sm-4 col-form-label fs-3">Surname:</label>
                <div class="col-sm-8">
			<input type="text" readonly class="form-control-plaintext fs-3" id="Surname" value="{{ user.last_name }}">
                </div>
            </div>
	    <!-- ГОРОД
            <div class="row">
                <label for="City" class="col-sm-4 col-form-label fs-3">City:</label>
                <div class="col-sm-8">
                    <input type="text" readonly class="form-control-plaintext fs-3" id="City" value="City">
                </div>
            </div>
	    -->
        </div>
	{% if places %}
        <div class="col-4">
	    {% for place in places %}
	    {% with category=place.categories.all %}
            {% for c in category %}
            <div class="row">
		    {% url 'main:detail' category_pk=c.pk pk=place.pk as url %}
		    <p>{{ place.title }}</p>
                    <a href="{{ url }}{{ all }}">
                    	<img id="user-place" class="img rounded" src="{% thumbnail place.image "200x200" %}">
                    </a>
            </div>
	    {% endfor %}
            {% endwith %}
	    {% endfor %}
        </div>
	{% endif %}
    </div>
    <footer>
        <div class="row" style="margin-top:250px">
            <div class="col-10"></div>

            <div class="col-2">
                <button type="button" class="btn btn-outline-secondary  btn-lg ">Удалить аккаунт</button>
            </div>

        </div>
    </footer>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js" integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4" crossorigin="anonymous"></script>
</body>
</html>  

src/users/templates/users/register_done.html
{% extends "layout/basic.html" %}

{% block content %}
<h2>Регистрация пользователя завершена.</h2>
<p>На адрес электронной почты, указанный пользователем, выслано письмо
для активации.</p>
<button onclick="document.location='{% url 'users:login' %}'" type='button'>Вернуться к входу</button>
{% endblock %}