src/here_point/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.contrib.staticfiles.views import serve
from django.views.decorators.cache import never_cache
from django.conf.urls.static import static


urlpatterns = [
    path('captcha/', include('captcha.urls')),
    path('accounts/', include('users.urls')),
    path('', include('main.urls')),
    path('admin/', admin.site.urls),

]

if settings.DEBUG:
    urlpatterns.append(path('static/<path:path>', never_cache(serve)))
    # Route for processing uploaded files
    urlpatterns += static(settings.MEDIA_URL, 
                          document_root=settings.MEDIA_ROOT)

src/main/urls.py
from django.urls import path

from .views import index, by_category, detail


app_name = 'main'
urlpatterns = [
    # path('accounts/login/', HerePointLoginView.as_view(), name='login'),
    path('', index, name='index'),
    path('<int:category_pk>/<int:pk>/', detail, name='detail'),
    path('<int:pk>/', by_category, name='by_category'),
]

src/users/urls.py
from django.urls import path

from .views import (HerePointLoginView, HerePointLogoutView, 
                    ChangeUserInfoView, RegisterDoneView, 
                    RegisterUserView, HerePointPasswordChangeView,
                    DeleteUserView)
from .views import (profile, profile_place_add, 
                    profile_place_delete, profile_place_change)


app_name = 'users'
urlpatterns = [
    path('profile/delete/', DeleteUserView.as_view(), name='profile_delete'),
    path('register/done/', RegisterDoneView.as_view(), name='register_done'),
    path('register/', RegisterUserView.as_view (), name='register'),
    path('profile/change/<int:pk>/', profile_place_change, name='place_change'),
    path('profile/delete/<int:pk>/', profile_place_delete, name='place_delete'),
    path('profile/add/', profile_place_add, name='place_add'),
    path('profile/', profile, name='profile'),
    path('login/', HerePointLoginView.as_view(), name='login'),
    path('logout/', HerePointLogoutView.as_view(), name='logout'),
    path('profile/change/', ChangeUserInfoView.as_view(), name='profile_change'),
    path('profile/password/change/', 
         HerePointPasswordChangeView.as_view(),
         name='password_change'),
]

src/main/models.py
from django.db import models

from .utilities import get_timestamp_path
from users.models import AdvUser


class Comment(models.Model):
    """ Model of comment """
    place = models.ForeignKey("Place", on_delete=models.CASCADE, 
                              verbose_name='Место')
    author = models.CharField(max_length=30, default='Гость', verbose_name='Автор')
    content = models.TextField(verbose_name='Содержание')
    is_active = models.BooleanField(default=True, db_index=True,
                                    verbose_name='Выводить на экран?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Опубликовано')

    class Meta:
        verbose_name_plural = 'Комментарии'
        verbose_name = 'Комментарий'
        ordering = ['created_at']


class Place(models.Model):
    """ Model of place """
    categories = models.ManyToManyField("Category", verbose_name='Категория')
    title = models.CharField(max_length=32, verbose_name='Место')
    description = models.TextField(verbose_name="Описание")
    address = models.CharField(max_length=64, verbose_name='Адрес')
    image = models.ImageField(upload_to=get_timestamp_path,
                              verbose_name='Изображение')
    author = models.ForeignKey(AdvUser, on_delete=models.CASCADE,
                               null=True, blank=False, 
                               verbose_name='Автор места')
    city = models.ForeignKey("City", on_delete=models.PROTECT,
                             verbose_name="Город")
    is_active = models.BooleanField(default=True, db_index=True,
                                  verbose_name='Выводить в списке?')
    created_at = models.DateTimeField(auto_now_add=True, db_index=True,
                                      verbose_name='Опубликовано')

    def _categories(self):
        return ", ".join([category.title for category in self.categories.all()])

    def delete(self, *args, **kwargs):
        """ Deleting additional images after removing place """
        for ai in self.additionalimage_set.all():
            ai.delete()
        super().delete(*args, **kwargs)

    def __str__(self):
        return self.title
    

    class Meta:
        verbose_name_plural = 'Места'
        verbose_name = 'Место'
        ordering = ['-created_at']


class AdditionalImage(models.Model):
    """ Additional image model """
    place = models.ForeignKey("Place", on_delete=models.CASCADE,
                              verbose_name='Место')
    image = models.ImageField(upload_to=get_timestamp_path,
                              verbose_name='Изображение')

    
    class Meta:
        verbose_name_plural = 'Дополнительные иллюстрации'
        verbose_name = 'Дополнительная иллюстрация'


class City(models.Model):
    title = models.CharField(max_length=32, verbose_name='Город')
    order = models.SmallIntegerField(default=0, db_index=True,
                                     verbose_name='Порядок')

    def __str__(self):
        return self.title


    class Meta:
        verbose_name_plural = 'Города'
        verbose_name = 'Город'


class Category(models.Model):
    """ Category model """
    title = models.CharField(max_length=32, db_index=True, unique=True,
                             verbose_name='Название')
    order = models.SmallIntegerField(default=0, db_index=True,
                                     verbose_name='Порядок')

    def __str__(self):
        return self.title


    class Meta:
        ordering = ('order', 'title')
        verbose_name = "Категория"
        verbose_name_plural = "Категории"


class AdvUser(AdvUser):
    def delete(self, *args, **kwargs):
        for p in self.place_set.all():
            p.delete()
        super().delete(*args, **kwargs)

src/main/forms.py
from django import forms
from captcha.fields import CaptchaField

from .models import Comment


class UserCommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        exclude = ('is_active',)
        widgets = {'place': forms.HiddenInput, 'author': forms.HiddenInput}


class GuestCommentForm(forms.ModelForm):
    captcha = CaptchaField(label='Введите текст с картинки',
                           error_messages={'invalid': "Неправильный текст"})
    
    class Meta:
        model = Comment
        exclude = ('is_active', 'author',)
        widgets = {'place': forms.HiddenInput}


class SearchForm(forms.Form):
    keyword = forms.CharField(required=False, max_length=32, label='')

src/main/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.views import LoginView
from django.core.paginator import Paginator
from django.db.models import Q

from .models import Category, Place, Comment
from .forms import SearchForm, UserCommentForm, GuestCommentForm


def by_category(request, pk):
    """ Get category from user's request """
    category = get_object_or_404(Category, pk=pk)
    places = Place.objects.filter(is_active=True, categories=pk)
    if 'keyword' in request.GET:
        keyword = request.GET['keyword']
        q = Q(title__icontains=keyword) | Q(description__icontains=keyword)
        places = places.filter(q)
    else:
        keyword = ''
    form = SearchForm(initial={'keyword': keyword})
    paginator = Paginator(places, 10)
    if 'page' in request.GET:
        page_num = request.GET['page']
    else:
        page_num = 1
    page = paginator.get_page(page_num)
    context = {"category": category, "page": page, 
               "places": page.object_list, "form": form}
    return render(request, 'by_category.html', context)

def detail(request, category_pk, pk):
    """ Displaying information about place """
    place = get_object_or_404(Place, pk=pk)
    ais = place.additionalimage_set.all()
    comments = Comment.objects.filter(place=pk, is_active=True)
    initial = {'place': place.pk}
    username = None
    author = place.author
    if request.user.is_authenticated:
        initial['author'] = request.user.username
        form_class = UserCommentForm
        username = request.user.username
    else:
        form_class = GuestCommentForm
    form = form_class(initial=initial)
    if request.method == "POST":
        c_form = form_class(request.POST)
        if c_form.is_valid():
            c_form.save()
        else:
            form = c_form
    numbers = []
    for number in range(len(ais)):
        numbers.append(number)
    category = place.categories.all()
    context = {'place': place, 'ais': ais, 'category': category,
               'comments': comments, 'form': form, 'numbers': numbers,
               'username': username, 'author': author}
    #if request.user.username:
    #    author = request.user.username
    #    context['author'] = author
    return render(request, 'place_info.html', context)

def index(request):
    places = Place.objects.filter(is_active=True)[:10]
    context = {'places': places}
    return render(request, 'primary_main.html', context)

src/main/templates/by_category.html
{% load static %}
{% load thumbnail %}
{% load bootstrap5 %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>main</title>
    <!-- bootstrap -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
        crossorigin="anonymous"></script>

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <link rel="stylesheet" href="{% static 'css/by_category.css' %}">
    <style>
        /* Monoserrat */
        @import url('https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap');
        /* Roboto */
        @import url('https://fonts.googleapis.com/css2?family=Roboto:wght@300;700&display=swap');
        
        #logo {
            text-decoration:none;
            color: #2b2a2c;
            font-size: 30px;
            padding: 0px 0px 0px 25px;
            font-family: 'Cinzel', serif;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
            position: relative;
        }

        #logo:after {
            content: "";
            /* display: block; */
            width: 100%;
            height: 2px;
            background-color: #2B2A2C;
            bottom: -5;
            left: 0;
            z-index: 1;
        }
    </style>
</head>
<body class="bg">
    <!-- Шапка -->
    <nav class="navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
		<a class="navbar-brand" style="margin: 8px;" href="{% url 'main:index' %}" id="logo">HerePoint</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto" style="align-items: center">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a href="{% url 'users:login' %}" class="nav-link">Добавить место</a>
                    </li>
                    <li class="nav-item active">
                        <img onclick="document.location='{% url 'users:profile' %}'" class="nav-link" src="{% static 'img/avatar_new.jpg' %}" width="60" height="60" alt="" style="border-radius: 50%;" id="usericon">
                    </li>
                    {% else %}
                    <li class="nav-item active">
			            <a href="{% url 'users:login' %}" class="nav-link">Войти</a>
                    </li>
                    <li class="nav-item active">
			            <a href="{% url 'users:register' %}" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item active">
                        <a href="#" class="nav-link text-center">Добавить место</a>
                    </li>
		            {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <hr style="margin-top: 0">
    <div class="container-fluid">
        <div class="row">
            <!-- Фильтры -->
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3">
                <div class="container filters rounded-bd">
                    <button class="btn btn-default btn-block shadow-none" type="button" id="buttonCollapse" 
                            data-toggle="collapse" data-target="#filterCollapse" aria-controls="filterCollapse" 
                            aria-expanded="true">
                        <span class="find-place"><b>Фильтр</b></span>
                    </button>
                    <div class="collapse show" id="filterCollapse">
                        <div class="container" style="padding: 10px;">
                            <form role="form" class="form-horizontal">
                                <div class="form-group label">
                                    <!-- Город -->
                                    <label for="select">Город</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>-не выбрано-</option>
                                        <option>Нижний Новгород</option>
                                    </select>
                                    <!-- Район -->
                                    <label for="select">Район</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>-не выбрано-</option>
                                    </select>
                                    <!-- Категория -->
                                    <label for="select">Категория</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>-не выбрано-</option>
                                        {% for category in categories %}
                                        <option><a href={% url 'main:by_category' pk=category.pk %}>{{ category.title }}</a>
                                        {% endfor %}
                                    </select>
                                    <!-- Сортировать по -->
                                    <label for="select">Сортировать</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>По рейтингу</option>
                                        <option>По названию</option>
                                        <option>По числу рекомендаций</option>
                                    </select>
                                </div>
                            </form>
                            {% for category in categories %}
                            <a href={% url 'main:by_category' pk=category.pk %}>{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Основной блок -->
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-8 col-xl-8 main-block rounded-bd">
                <!-- Название категории -->
                <div class="row" style="align-items: center; margin-bottom: 1em;">
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <h2>{{ category }}</h2>
                    </div>
                    <div class="col-xs-12 col-sm-12 col-md-6 col-lg-6 col-xl-6">
                        <form id="form-search" method='get'>
                            <input id="input-search" name='keyword' type='text' placeholder="Искать здесь...">
                            <button id="button-search" type='submit'></button>
                        </form>
                    </div>
                </div>
                <!-- Места -->
		        {% if places %}
                <div class="row">
                    {% for place in places %}
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                        <div class="container rounded-bd places">
                            <!-- Ссылка на место -->
                            {% url 'main:detail' category_pk=category.pk pk=place.pk as url %}
                            <a href="{{ url }}{{ all }}" class="text-decoration-none">
                                <div class="row" style="align-items: center;">
                                    <div class="col-xs-4 col-sm-4 col-md-5 col-lg-5 col-xl-5">
                                            <img class="img rounded" src="{% thumbnail place.image "300x300" %}">
                                    </div>
                                    <div class="col-xs-8 col-sm-8 col-md-7 col-lg-7 col-xl-7">
                                        <p>{{ place.title }}</p>
                                        <hr>
                                        <p>Адрес: {{ place.address }}</p>
                                        <hr>
                                        <p>Рейтинг: <span style="font-size:20px">4.7</span>/5</p>
                                    </div>
                                </div>
                            </a>
                        </div>
                    </div>
                    {% endfor %}
                </div>
                {% endif %}
                {% bootstrap_pagination page url=keyword %}
            </div>
        </div>
    </div>
    <footer>
        <script src="{% static 'js/scripts.js' %}"></script>
    </footer>
</body>
</html>

src/main/templates/primary_main.html
{% load static %}
{% load thumbnail %}

<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">

    <title>main</title>
    <!-- bootstrap 4 -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" 
        integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" 
        crossorigin="anonymous">
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" 
        integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" 
        crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" 
        integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" 
        crossorigin="anonymous"></script>

    <!-- bootstrap 5 -->
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" 
        integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" 
        crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" 
        integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" 
        crossorigin="anonymous"></script> -->

    <!-- jQuery -->
    <!-- <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" 
        integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" 
        crossorigin="anonymous"></script> -->

    <link rel="stylesheet" href="{% static 'css/main.css' %}">
    <style>
        @import url('https://fonts.googleapis.com/css2?family=Cinzel&family=Montserrat:wght@100&display=swap');
	    @import url('https://fonts.googleapis.com/css2?family=Open+Sans+Condensed:wght@300&display=swap');
        #logo {
            text-decoration:none;
            color: #2b2a2c;
            font-size: 30px;
            font-family: 'Cinzel', serif;
            font-family: 'Montserrat', sans-serif;
            font-weight: 600;
        }
	
    </style>
</head>
<body class="bg">
    <!-- Шапка -->
    <nav class="navbar navbar-expand-md navbar-light">
        <div class="container-fluid">
		<a class="navbar-brand" style="margin: 8px;" href="{% url 'main:index' %}" id="logo">HerePoint</a>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarResponsive">
                <ul class="navbar-nav ml-auto" style="align-items: center">
                    {% if user.is_authenticated %}
                    <li class="nav-item active">
                        <a href="{% url 'users:profile_place_add' %}" class="nav-link">Добавить место</a>
                    </li>
                    <li class="nav-item active">
                        <img onclick="document.location='{% url 'users:profile' %}'" class="nav-link" src="{% static 'img/avatar_new.jpg' %}" width="60" height="60" alt="" style="border-radius: 50%;" id="usericon">
                    </li>
                    {% else %}
                    <li class="nav-item active">
			            <a href="{% url 'users:login' %}" class="nav-link">Войти</a>
                    </li>
                    <li class="nav-item active">
			            <a href="{% url 'users:register' %}" class="nav-link">Регистрация</a>
                    </li>
                    <li class="nav-item active">
                        <a href="{% url 'users:login' %}" class="nav-link text-center">Добавить место</a>
                    </li>
		            {% endif %}
                </ul>
            </div>
        </div>
    </nav>
    <hr style="margin-top: 0">
    <div class="container-fluid">
        <div class="row">
            <!-- Фильтры -->
            <div class="col-xs-12 col-sm-12 col-md-4 col-lg-3 col-xl-3">
                <div class="container filters rounded-bd">
                    <button class="btn btn-default btn-block shadow-none" type="button" id="buttonCollapse" 
                            data-toggle="collapse" data-target="#filterCollapse" aria-controls="filterCollapse" 
                            aria-expanded="true">
                        <span class="find-place"><b>Фильтр</b></span>
                    </button>
                    <div class="collapse show" id="filterCollapse">
                        <div class="container" style="padding: 10px;">
                            <form role="form" class="form-horizontal">
                                <div class="form-group label">
                                    <!-- Город -->
                                    <label for="select">Город</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>-не выбрано-</option>
                                        <option>Нижний Новгород</option>
                                    </select>
                                    <!-- Район -->
                                    <label for="select">Район</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>-не выбрано-</option>
                                    </select>
                                    <!-- Категория -->
                                    <label for="select">Категория</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
					                    <option>-не выбрано-</option>
					                    {% for category in categories %}
					                    <option><a href={% url 'main:by_category' pk=category.pk %}>{{ category.title }}</a>
					                    {% endfor %}
                                    </select>
                                    <!-- Сортировать по -->
                                    <label for="select">Сортировать</label>
                                    <select class="form-control" name="city" id="city" style="font-size: 14px;">
                                        <option>По рейтингу</option>
                                        <option>По названию</option>
                                        <option>По числу рекомендаций</option>
                                    </select>
                                </div>
                            </form>
                            {% for category in categories %}
                            <a href={% url 'main:by_category' pk=category.pk %}>{{ category.title }}</a>
                            {% endfor %}
                        </div>
                    </div>
                </div>
            </div>
            <!-- Основной блок -->
            <div class="col-xs-12 col-sm-12 col-md-6 col-lg-8 col-xl-8 main-block rounded-bd">
                <!-- Места -->
                <div class="row">
                    {% for place in places %}
                    <div class="col-xs-12 col-sm-12 col-md-12 col-lg-6 col-xl-6">
                        <div class="container rounded-bd places">
                            <!-- Ссылка на место -->
                            {% with category=place.categories.all %}
                            {% for c in category %}
                            {% url 'main:detail' category_pk=c.pk pk=place.pk as url %}
                            <a href="{{ url }}{{ all }}" class="text-decoration-none">
                                <div class="row" style="align-items: center;">
                                    <div class="col-xs-4 col-sm-4 col-md-5 col-lg-5 col-xl-5">
                                        <img class="img rounded" src="{% thumbnail place.image "300x300" %}">
                                    </div>
                                    <div class="col-xs-8 col-sm-8 col-md-7 col-lg-7 col-xl-7">
                                        <p>{{ place.title }}</p>
                                        <hr>
                                        <p>{{ place.address }}</p>
                                        <hr>
                                        <p>Рейтинг: <span style="font-size:20px">4.7</span>/5</p>
                                    </div>
                                </div>
                            </a>
                            {% endfor %}
                            {% endwith %}
                        </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
        </div>
    </div>
    <footer>
        <script src="{% static 'js/scripts.js' %}"></script>
    </footer>
</body>
</html>